### ISSUE TITLE
Link support and title constant

### ISSUE THREAD

**Issue by Alerinos** [jsakamoto/Toolbelt.Blazor.HeadElement#21]
Hi, what do you think to do to support:
`<link rel ...> `or for `<style>`?
Quite often we need to load a specific style only for a specific subpage, so why load it when the user does not enter there?

Alternatively, you can also add <script> so that it loads in the footer, sometimes we want to quickly add a script or a ready-made library, e.g. "datatables"

Another idea is to add a constant variable to title, sometimes there are cases where we want to make "page name - site name". Site name is constant on every page so it would be nice if it was automatically added.

These are just my suggestions, you are doing a really good job.

**Comment by jsakamoto** [comment]
Thank you for the proposal!

> Hi, what do you think to do to support:
> <link rel ...> or for <style>?

Maybe as already you know, manipulating "<link ...>" elements in a head element are supported by this library.
"<style>" elements are not supported but it can be alternated by "<link rel='stylesheet' href='...'/>".

> Alternatively, you can also add <script> so that it loads in the footer, sometimes we want to quickly add a script or a ready-made library, e.g. "datatables"

Add support for adding "<script>" elements is hard work for me because it will cause numerous side effects.
So I have no plan to add support for adding "<script>" elements at this time.
I appreciate your understanding.

> Another idea is to add a constant variable to title, 

Yes, this is the request I most receive. :)
I understand so many people request this feature for me, but this means there are so many various versions of those requests.
So I think it's hard to make all those people satisfied with this topic.

Fortunately, adding a constant variable to the title by the user's hand is easy.
One of the examples, you can write a simple Blazor component to do it like this:

```
@* CustomTitle.razor *@
<Title>@PageName - site name</Title>
@code {
[Parameter] public string PageName {get;set;}
}
```
After doing that, you can use this your custom component in your Blazor app.

```
<CustomTitle PageName="Home" />
```

Above sample code is just one of the examples. There are so many various solutions to do it.

Therefore, the feature adding a constant variable to the title is not planed yet.

Anyway, thanks for many suggestions!
